# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgateway.proto\x12\x07gateway\"#\n\rHealthRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"5\n\x0eHealthResponse\x12#\n\x06status\x18\x01 \x01(\x0e\x32\x13.gateway.StatusType\"D\n\x0cTaskResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x10\n\x08response\x18\x03 \x01(\t\"T\n\x0bTaskRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12 \n\x04type\x18\x03 \x01(\x0e\x32\x12.gateway.EventType*-\n\tEventType\x12\x10\n\x0cPROMPT_EVENT\x10\x00\x12\x0e\n\nTOOL_EVENT\x10\x01*_\n\nStatusType\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n\rSTATUS_ACTIVE\x10\x01\x12\x13\n\x0fSTATUS_DEFERRED\x10\x02\x12\x11\n\rSTATUS_FAILED\x10\x03\x32\x87\x01\n\rAttilaGateway\x12\x39\n\x06Health\x12\x16.gateway.HealthRequest\x1a\x17.gateway.HealthResponse\x12;\n\nSubmitTask\x12\x14.gateway.TaskRequest\x1a\x15.gateway.TaskResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTTYPE']._serialized_start=274
  _globals['_EVENTTYPE']._serialized_end=319
  _globals['_STATUSTYPE']._serialized_start=321
  _globals['_STATUSTYPE']._serialized_end=416
  _globals['_HEALTHREQUEST']._serialized_start=26
  _globals['_HEALTHREQUEST']._serialized_end=61
  _globals['_HEALTHRESPONSE']._serialized_start=63
  _globals['_HEALTHRESPONSE']._serialized_end=116
  _globals['_TASKRESPONSE']._serialized_start=118
  _globals['_TASKRESPONSE']._serialized_end=186
  _globals['_TASKREQUEST']._serialized_start=188
  _globals['_TASKREQUEST']._serialized_end=272
  _globals['_ATTILAGATEWAY']._serialized_start=419
  _globals['_ATTILAGATEWAY']._serialized_end=554
# @@protoc_insertion_point(module_scope)
